version: "3.9"
services:
  db:
    hostname: localhost
    image: ankane/pgvector
    restart: always
    container_name: postgres-for-coursechat
    ports:
      - "${DB_PORT}:5432" # HOST_PORT:CONTAINER_PORT
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql